name: python-deployment  # Назва workflow, яка відображатиметься в GitHub Actions UI
run-name: ${{ github.actor }} - ${{ github.ref }}# хто запустив та що запустили

on:
  push:
    branches: [main]  # Запускати workflow при пуші в гілку main
  pull_request:
    branches: [main] # Запускати workflow при створенні pull request в гілку main

    jobs:
      python-ci:
        runs-on ubuntu-latest  # Використовувати останню версію Ubuntu для виконання job

        steps:

        - uses: actions/checkout@v4  # Крок для перевірки коду з репозиторію
